development:
  database:
    name: postgres
    host: localhost
    port: 5432
    user: postgres
    password: 12345678
    dbname: mur_user
    sslmode: disable
    timezone: Asia/Yangon

testing:
  database:
    name: sqlite